### ISSUE TITLE
U1 MLF8 alterative?

### ISSUE THREAD

**Issue by kgarrels** [skuep/AIOC#24]
Is there an alternative for U1? JLCPCB did not have them, and hand-soldering seems impossible with MLF8.

Any hint would be appreciated!

U1,MIC5330-SSYML,Micrel_MLF-8-1EP_2x2mm_P0.5mm_EP0.6x1.2mm

Thanks,
kai

**Comment by skuep** [comment]
Unfortunately, no alternative. 
However: See this issue here: 
https://github.com/skuep/AIOC/issues/23
Basically, JLCPCB allows you to order parts from other distributors (i.e. Digi-Key or Mouser) so that JLCPCB can mount them for you. It's very easy to order the parts from Digi-Key/Mouser through the JLCPCB interface.

**Comment by kgarrels** [comment]
Very good tip, thanks a lot!Von meinem iPhone gesendetAm 27.04.2023 um 19:48 schrieb Simon Küppers ***@***.***>:﻿
Unfortunately, no alternative.
However: See this issue here:
#23
Basically, JLCPCB allows you to order parts from other distributors (i.e. Digi-Key or Mouser) so that JLCPCB can mount them for you. It's very easy to order the parts from Digi-Key/Mouser through the JLCPCB interface.
