### ISSUE TITLE
NOT AN ISSUE JUST A FYI

### ISSUE THREAD

**Issue by WROG208** [skuep/AIOC#78]
I made my first AIOC just like you guys recommended, I will be using this on a GMRS and Allstar Link setup and was getting a lot of RF interference that was locking the AIOC on constant PTT mode and other weird behavior. I opted to try [these 2.5 Pigtails](https://www.amazon.com/gp/product/B08Z7LNTVW/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1) from amazon and [these 3.5 pigtails](https://www.amazon.com/gp/product/B082VW49VV/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1) and I can confirm they work well and there is no more RF interference.
Not to mention they are way easier to solder to the board and no soldering guide is needed.

HOPE this helps others.
![20240714_014608](https://github.com/user-attachments/assets/fcfd97b9-766f-4217-b03e-38356d173968)

**Comment by skuep** [comment]
Hi, thanks for your message! :-)
Unfortunately this is probably not quite the right place for this, because I am currently closing stale issues and this information will be hidden away by GitHub (by default it only shows active issues). 
I think it might be a good idea to post this to the discord channel and be able to discuss with other people.
